// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function ExportProductsToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportProductsToCSV'](arg1, arg2);
}

export function ExportProductsToXLSX(arg1, arg2) {
  return window['go']['main']['App']['ExportProductsToXLSX'](arg1, arg2);
}

export function GetAllProducts(arg1) {
  return window['go']['main']['App']['GetAllProducts'](arg1);
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetImportTemplate() {
  return window['go']['main']['App']['GetImportTemplate']();
}

export function GetProduct(arg1) {
  return window['go']['main']['App']['GetProduct'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportProductsFromCSV(arg1) {
  return window['go']['main']['App']['ImportProductsFromCSV'](arg1);
}

export function ImportProductsFromXLSX(arg1) {
  return window['go']['main']['App']['ImportProductsFromXLSX'](arg1);
}

export function RetryDatabaseConnection() {
  return window['go']['main']['App']['RetryDatabaseConnection']();
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3);
}
