// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {pagination_dto} from '../models';

export function CreateProduct(arg1:string,arg2:number):Promise<core.Product>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GetAllProducts(arg1:pagination_dto.PaginationDTO):Promise<core.PaginationResponse>;

export function GetDatabaseStatus():Promise<Record<string, any>>;

export function GetProduct(arg1:number):Promise<core.Product>;

export function Greet(arg1:string):Promise<string>;

export function RetryDatabaseConnection():Promise<Record<string, any>>;

export function UpdateProduct(arg1:number,arg2:string,arg3:number):Promise<core.Product>;
