// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1, arg2) {
  return window['go']['main']['App']['CreateProduct'](arg1, arg2);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function GetAllProducts() {
  return window['go']['main']['App']['GetAllProducts']();
}

export function GetProduct(arg1) {
  return window['go']['main']['App']['GetProduct'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3);
}
